# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Pump
ARDUINO_LIBS := AUnit
ARDUINO_LIB_DIRS := \
	/Users/zalleon/Documents/PlatformIO/Projects/AutomaticWaterringSystem/.pio/libdeps/nanoatmega328
include /Users/zalleon/Documents/PlatformIO/Projects/EpoxyDuino/EpoxyDuino.mk

